# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@dfinity/agent-0.9.0" = {
      name = "_at_dfinity_slash_agent";
      packageName = "@dfinity/agent";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dfinity/agent/-/agent-0.9.0.tgz";
        sha512 = "htD+ZpaP0MOKcHADo+9Tb+HqBkBySQYFXlEryEnLmvf1oMriDrw8O9m+7BaKQ89gMI1qFftkl4BGnWwd/oUrIg==";
      };
    };
    "@dfinity/candid-0.9.0" = {
      name = "_at_dfinity_slash_candid";
      packageName = "@dfinity/candid";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dfinity/candid/-/candid-0.9.0.tgz";
        sha512 = "03A9NUTwAj/+/VGWeIeexKELXgyWIRlSnDoJwMAGHoxJ+fX/Zy7gkk/vLnHWGXmAMm1R18wm+WStmdLzR16ztQ==";
      };
    };
    "@dfinity/principal-0.9.0" = {
      name = "_at_dfinity_slash_principal";
      packageName = "@dfinity/principal";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dfinity/principal/-/principal-0.9.0.tgz";
        sha512 = "0pCoz6HUxb7L7wQZ0k4yBQ6gB2pbf3ld7W5JbAoaLGhI+TuR7PxoX2+SBJikWqEjnpEiFSobYPBs7UmYsTm8yg==";
      };
    };
    "@discoveryjs/json-ext-0.5.3" = {
      name = "_at_discoveryjs_slash_json-ext";
      packageName = "@discoveryjs/json-ext";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@discoveryjs/json-ext/-/json-ext-0.5.3.tgz";
        sha512 = "Fxt+AfXgjMoin2maPIYzFZnQjAXjAL0PHscM5pRTtatFqB+vZxAM9tLp2Optnuw3QOQC40jTNeGYFOMvyf7v9g==";
      };
    };
    "@types/eslint-7.2.13" = {
      name = "_at_types_slash_eslint";
      packageName = "@types/eslint";
      version = "7.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/eslint/-/eslint-7.2.13.tgz";
        sha512 = "LKmQCWAlnVHvvXq4oasNUMTJJb2GwSyTY8+1C7OH5ILR8mPLaljv1jxL1bXW3xB3jFbQxTKxJAvI8PyjB09aBg==";
      };
    };
    "@types/eslint-scope-3.7.0" = {
      name = "_at_types_slash_eslint-scope";
      packageName = "@types/eslint-scope";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/eslint-scope/-/eslint-scope-3.7.0.tgz";
        sha512 = "O/ql2+rrCUe2W2rs7wMR+GqPRcgB6UiqN5RhrR5xruFlY7l9YLMn0ZkDzjoHLeiFkR8MCQZVudUuuvQ2BLC9Qw==";
      };
    };
    "@types/estree-0.0.46" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.46";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.46.tgz";
        sha512 = "laIjwTQaD+5DukBZaygQ79K1Z0jb1bPEMRrkXSLjtCcZm+abyp5YbrqpSLzD42FwWW6gK/aS4NYpJ804nG2brg==";
      };
    };
    "@types/html-minifier-terser-5.1.1" = {
      name = "_at_types_slash_html-minifier-terser";
      packageName = "@types/html-minifier-terser";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/html-minifier-terser/-/html-minifier-terser-5.1.1.tgz";
        sha512 = "giAlZwstKbmvMk1OO7WXSj4OZ0keXAcl2TQq4LWHiiPH2ByaH7WeUzng+Qej8UPxxv+8lRTuouo0iaNDBuzIBA==";
      };
    };
    "@types/json-schema-7.0.7" = {
      name = "_at_types_slash_json-schema";
      packageName = "@types/json-schema";
      version = "7.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.7.tgz";
        sha512 = "cxWFQVseBm6O9Gbw1IWb8r6OS4OhSt3hPZLkFApLjM8TEXROBuQGLAH2i2gZpcXdLBIrpXuTDhH7Vbm1iXmNGA==";
      };
    };
    "@types/node-15.12.2" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "15.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-15.12.2.tgz";
        sha512 = "zjQ69G564OCIWIOHSXyQEEDpdpGl+G348RAKY0XXy9Z5kU9Vzv1GMNnkar/ZJ8dzXB3COzD9Mo9NtRZ4xfgUww==";
      };
    };
    "@webassemblyjs/ast-1.11.0" = {
      name = "_at_webassemblyjs_slash_ast";
      packageName = "@webassemblyjs/ast";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/ast/-/ast-1.11.0.tgz";
        sha512 = "kX2W49LWsbthrmIRMbQZuQDhGtjyqXfEmmHyEi4XWnSZtPmxY0+3anPIzsnRb45VH/J55zlOfWvZuY47aJZTJg==";
      };
    };
    "@webassemblyjs/floating-point-hex-parser-1.11.0" = {
      name = "_at_webassemblyjs_slash_floating-point-hex-parser";
      packageName = "@webassemblyjs/floating-point-hex-parser";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/floating-point-hex-parser/-/floating-point-hex-parser-1.11.0.tgz";
        sha512 = "Q/aVYs/VnPDVYvsCBL/gSgwmfjeCb4LW8+TMrO3cSzJImgv8lxxEPM2JA5jMrivE7LSz3V+PFqtMbls3m1exDA==";
      };
    };
    "@webassemblyjs/helper-api-error-1.11.0" = {
      name = "_at_webassemblyjs_slash_helper-api-error";
      packageName = "@webassemblyjs/helper-api-error";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-api-error/-/helper-api-error-1.11.0.tgz";
        sha512 = "baT/va95eXiXb2QflSx95QGT5ClzWpGaa8L7JnJbgzoYeaA27FCvuBXU758l+KXWRndEmUXjP0Q5fibhavIn8w==";
      };
    };
    "@webassemblyjs/helper-buffer-1.11.0" = {
      name = "_at_webassemblyjs_slash_helper-buffer";
      packageName = "@webassemblyjs/helper-buffer";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-buffer/-/helper-buffer-1.11.0.tgz";
        sha512 = "u9HPBEl4DS+vA8qLQdEQ6N/eJQ7gT7aNvMIo8AAWvAl/xMrcOSiI2M0MAnMCy3jIFke7bEee/JwdX1nUpCtdyA==";
      };
    };
    "@webassemblyjs/helper-numbers-1.11.0" = {
      name = "_at_webassemblyjs_slash_helper-numbers";
      packageName = "@webassemblyjs/helper-numbers";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-numbers/-/helper-numbers-1.11.0.tgz";
        sha512 = "DhRQKelIj01s5IgdsOJMKLppI+4zpmcMQ3XboFPLwCpSNH6Hqo1ritgHgD0nqHeSYqofA6aBN/NmXuGjM1jEfQ==";
      };
    };
    "@webassemblyjs/helper-wasm-bytecode-1.11.0" = {
      name = "_at_webassemblyjs_slash_helper-wasm-bytecode";
      packageName = "@webassemblyjs/helper-wasm-bytecode";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-wasm-bytecode/-/helper-wasm-bytecode-1.11.0.tgz";
        sha512 = "MbmhvxXExm542tWREgSFnOVo07fDpsBJg3sIl6fSp9xuu75eGz5lz31q7wTLffwL3Za7XNRCMZy210+tnsUSEA==";
      };
    };
    "@webassemblyjs/helper-wasm-section-1.11.0" = {
      name = "_at_webassemblyjs_slash_helper-wasm-section";
      packageName = "@webassemblyjs/helper-wasm-section";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-wasm-section/-/helper-wasm-section-1.11.0.tgz";
        sha512 = "3Eb88hcbfY/FCukrg6i3EH8H2UsD7x8Vy47iVJrP967A9JGqgBVL9aH71SETPx1JrGsOUVLo0c7vMCN22ytJew==";
      };
    };
    "@webassemblyjs/ieee754-1.11.0" = {
      name = "_at_webassemblyjs_slash_ieee754";
      packageName = "@webassemblyjs/ieee754";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/ieee754/-/ieee754-1.11.0.tgz";
        sha512 = "KXzOqpcYQwAfeQ6WbF6HXo+0udBNmw0iXDmEK5sFlmQdmND+tr773Ti8/5T/M6Tl/413ArSJErATd8In3B+WBA==";
      };
    };
    "@webassemblyjs/leb128-1.11.0" = {
      name = "_at_webassemblyjs_slash_leb128";
      packageName = "@webassemblyjs/leb128";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/leb128/-/leb128-1.11.0.tgz";
        sha512 = "aqbsHa1mSQAbeeNcl38un6qVY++hh8OpCOzxhixSYgbRfNWcxJNJQwe2rezK9XEcssJbbWIkblaJRwGMS9zp+g==";
      };
    };
    "@webassemblyjs/utf8-1.11.0" = {
      name = "_at_webassemblyjs_slash_utf8";
      packageName = "@webassemblyjs/utf8";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/utf8/-/utf8-1.11.0.tgz";
        sha512 = "A/lclGxH6SpSLSyFowMzO/+aDEPU4hvEiooCMXQPcQFPPJaYcPQNKGOCLUySJsYJ4trbpr+Fs08n4jelkVTGVw==";
      };
    };
    "@webassemblyjs/wasm-edit-1.11.0" = {
      name = "_at_webassemblyjs_slash_wasm-edit";
      packageName = "@webassemblyjs/wasm-edit";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-edit/-/wasm-edit-1.11.0.tgz";
        sha512 = "JHQ0damXy0G6J9ucyKVXO2j08JVJ2ntkdJlq1UTiUrIgfGMmA7Ik5VdC/L8hBK46kVJgujkBIoMtT8yVr+yVOQ==";
      };
    };
    "@webassemblyjs/wasm-gen-1.11.0" = {
      name = "_at_webassemblyjs_slash_wasm-gen";
      packageName = "@webassemblyjs/wasm-gen";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-gen/-/wasm-gen-1.11.0.tgz";
        sha512 = "BEUv1aj0WptCZ9kIS30th5ILASUnAPEvE3tVMTrItnZRT9tXCLW2LEXT8ezLw59rqPP9klh9LPmpU+WmRQmCPQ==";
      };
    };
    "@webassemblyjs/wasm-opt-1.11.0" = {
      name = "_at_webassemblyjs_slash_wasm-opt";
      packageName = "@webassemblyjs/wasm-opt";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-opt/-/wasm-opt-1.11.0.tgz";
        sha512 = "tHUSP5F4ywyh3hZ0+fDQuWxKx3mJiPeFufg+9gwTpYp324mPCQgnuVKwzLTZVqj0duRDovnPaZqDwoyhIO8kYg==";
      };
    };
    "@webassemblyjs/wasm-parser-1.11.0" = {
      name = "_at_webassemblyjs_slash_wasm-parser";
      packageName = "@webassemblyjs/wasm-parser";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wasm-parser/-/wasm-parser-1.11.0.tgz";
        sha512 = "6L285Sgu9gphrcpDXINvm0M9BskznnzJTE7gYkjDbxET28shDqp27wpruyx3C2S/dvEwiigBwLA1cz7lNUi0kw==";
      };
    };
    "@webassemblyjs/wast-printer-1.11.0" = {
      name = "_at_webassemblyjs_slash_wast-printer";
      packageName = "@webassemblyjs/wast-printer";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/wast-printer/-/wast-printer-1.11.0.tgz";
        sha512 = "Fg5OX46pRdTgB7rKIUojkh9vXaVN6sGYCnEiJN1GYkb0RPwShZXp6KTDqmoMdQPKhcroOXh3fEzmkWmCYaKYhQ==";
      };
    };
    "@webpack-cli/configtest-1.0.3" = {
      name = "_at_webpack-cli_slash_configtest";
      packageName = "@webpack-cli/configtest";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webpack-cli/configtest/-/configtest-1.0.3.tgz";
        sha512 = "WQs0ep98FXX2XBAfQpRbY0Ma6ADw8JR6xoIkaIiJIzClGOMqVRvPCWqndTxf28DgFopWan0EKtHtg/5W1h0Zkw==";
      };
    };
    "@webpack-cli/info-1.2.4" = {
      name = "_at_webpack-cli_slash_info";
      packageName = "@webpack-cli/info";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webpack-cli/info/-/info-1.2.4.tgz";
        sha512 = "ogE2T4+pLhTTPS/8MM3IjHn0IYplKM4HbVNMCWA9N4NrdPzunwenpCsqKEXyejMfRu6K8mhauIPYf8ZxWG5O6g==";
      };
    };
    "@webpack-cli/serve-1.4.0" = {
      name = "_at_webpack-cli_slash_serve";
      packageName = "@webpack-cli/serve";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webpack-cli/serve/-/serve-1.4.0.tgz";
        sha512 = "xgT/HqJ+uLWGX+Mzufusl3cgjAcnqYYskaB7o0vRcwOEfuu6hMzSILQpnIzFMGsTaeaX4Nnekl+6fadLbl1/Vg==";
      };
    };
    "@xtuc/ieee754-1.2.0" = {
      name = "_at_xtuc_slash_ieee754";
      packageName = "@xtuc/ieee754";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xtuc/ieee754/-/ieee754-1.2.0.tgz";
        sha512 = "DX8nKgqcGwsc0eJSqYt5lwP4DH5FlHnmuWWBRy7X0NcaGR0ZtuyeESgMwTYVEtxmsNGY+qit4QYT/MIYTOTPeA==";
      };
    };
    "@xtuc/long-4.2.2" = {
      name = "_at_xtuc_slash_long";
      packageName = "@xtuc/long";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xtuc/long/-/long-4.2.2.tgz";
        sha512 = "NuHqBY1PB/D8xU6s/thBgOAiAP7HOYDQ32+BFZILJ8ivkUkAHQnWfn6WhL79Owj1qmUnoN/YPhktdIoucipkAQ==";
      };
    };
    "acorn-8.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.3.0.tgz";
        sha512 = "tqPKHZ5CaBJw0Xmy0ZZvLs1qTV+BNFSyvn77ASXkpBNfIRk8ev26fKrD9iLGwGA9zedPao52GSHzq8lyZG0NUw==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ajv-keywords-3.5.2" = {
      name = "ajv-keywords";
      packageName = "ajv-keywords";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-3.5.2.tgz";
        sha512 = "5p6WTN0DdTGVQk6VjcEju19IgaHudalcfabD7yhDGeA6bcQnmL+CpveLJq/3hvfwd1aof6L386Ougkx6RfyMIQ==";
      };
    };
    "ansi-colors-4.1.1" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz";
        sha512 = "JoX0apGbHaUJBNl6yF+p6JAFYZ666/hhCGKN5t9QFjbJQKUU/g8MNbFDbvfrgKXvI1QpZplPOnwIo99lX/AAmA==";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "base64-arraybuffer-0.2.0" = {
      name = "base64-arraybuffer";
      packageName = "base64-arraybuffer";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.2.0.tgz";
        sha512 = "7emyCsu1/xiBXgQZrscw/8KPRT44I4Yq9Pe6EGs3aPRTsWuggML1/1DTuZUuIaJPIm1FTDUVXl4x/yW8s0kQDQ==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "big.js-5.2.2" = {
      name = "big.js";
      packageName = "big.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-5.2.2.tgz";
        sha512 = "vyL2OymJxmarO8gxMr0mhChsO9QGwhynfuu4+MHTAW6czfq9humCB7rKpUjDd9YUiDPU4mzpyupFSvOClAwbmQ==";
      };
    };
    "bigint-json-native-0.4.2" = {
      name = "bigint-json-native";
      packageName = "bigint-json-native";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bigint-json-native/-/bigint-json-native-0.4.2.tgz";
        sha512 = "5gaz3Q7M/O9iasxtdaRLLClzd1zHTx/Tcd499nn0YvEJgnRbiFkBM0qOmlgI+g1FJ85IuMCR0g18dKE+X3wAtA==";
      };
    };
    "bignumber.js-7.2.1" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-7.2.1.tgz";
        sha512 = "S4XzBk5sMB+Rcb/LNcpzXr57VRTxgAvaAEDAl1AwRx27j00hT84O6OkteE7u8UB3NuaaygCRrEpqox4uDOrbdQ==";
      };
    };
    "bignumber.js-9.0.1" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-9.0.1.tgz";
        sha512 = "IdZR9mh6ahOBv/hYGiXyVuyCetmGJhtYkqLBpTStdhEGjegpPlUawydyaF3pbIOFynJTpllEs+NP+CS9jKFLjA==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "borc-2.1.2" = {
      name = "borc";
      packageName = "borc";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/borc/-/borc-2.1.2.tgz";
        sha512 = "Sy9eoUi4OiKzq7VovMn246iTo17kzuyHJKomCfpWMlI6RpfN1gk95w7d7gH264nApVLg0HZfcpz62/g4VH1Y4w==";
      };
    };
    "browserslist-4.16.6" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.16.6.tgz";
        sha512 = "Wspk/PqO+4W9qp5iUTJsa1B/QrYn1keNCcEP5OvP7WBwT4KaDly0uONYmC6Xa3Z5IqnUgS0KcgLYu1l74x0ZXQ==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-pipe-0.0.4" = {
      name = "buffer-pipe";
      packageName = "buffer-pipe";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-pipe/-/buffer-pipe-0.0.4.tgz";
        sha512 = "8cHio1V6wgX+LIX6+af4tCn0+Ljl2vQd9JZdZ8vDJZdDf8x5p2DneKaq1dWxSswJG+sK4Inok9aqoqILG5kQVQ==";
      };
    };
    "camel-case-4.1.2" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-4.1.2.tgz";
        sha512 = "gxGWBrTT1JuMx6R+o5PTXMmUnhnVzLQ9SNutD4YqKtI6ap897t3tKECYla6gCWEkplXnlNybEkZg9GEGxKFCgw==";
      };
    };
    "caniuse-lite-1.0.30001236" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001236";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001236.tgz";
        sha512 = "o0PRQSrSCGJKCPZcgMzl5fUaj5xHe8qA2m4QRvnyY4e1lITqoNkr7q/Oh1NcpGSy0Th97UZ35yoKcINPoq7YOQ==";
      };
    };
    "chrome-trace-event-1.0.3" = {
      name = "chrome-trace-event";
      packageName = "chrome-trace-event";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-trace-event/-/chrome-trace-event-1.0.3.tgz";
        sha512 = "p3KULyQg4S7NIHixdwbGX+nFHkoBiA4YQmyWtjb8XngSKV124nJmRysgAeujbUVb15vh+RvFUfCPqU7rXk+hZg==";
      };
    };
    "clean-css-4.2.3" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-4.2.3.tgz";
        sha512 = "VcMWDN54ZN/DS+g58HYL5/n4Zrqe8vHJpGA8KdgUXFU4fuP/aHNw8eld9SyEIyabIMJX/0RaY/fplOo5hYLSFA==";
      };
    };
    "clone-deep-4.0.1" = {
      name = "clone-deep";
      packageName = "clone-deep";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-deep/-/clone-deep-4.0.1.tgz";
        sha512 = "neHB9xuzh/wk0dIHweyAXv2aPGZIVk3pLMe+/RNzINf17fe0OG96QroktYAUm7SM1PBnzTabaLboqqxDyMU+SQ==";
      };
    };
    "colorette-1.2.2" = {
      name = "colorette";
      packageName = "colorette";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-1.2.2.tgz";
        sha512 = "MKGMzyfeuutC/ZJ1cba9NqcNpfeqMUcYmyF1ZFY6/Cn7CNSAKx6a+s48sqLqyAiZuaP2TcqMhoo+dlwFnVxT9w==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-4.1.1" = {
      name = "commander";
      packageName = "commander";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-4.1.1.tgz";
        sha512 = "NOKm8xhkzAjzFx8B2v5OAHT+u5pRQc2UCa2Vq9jYL/31o2wi9mxBA7LIFs3sV5VSC49z6pEhfbMULvShKj26WA==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "css-loader-5.2.6" = {
      name = "css-loader";
      packageName = "css-loader";
      version = "5.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-loader/-/css-loader-5.2.6.tgz";
        sha512 = "0wyN5vXMQZu6BvjbrPdUJvkCzGEO24HC7IS7nW4llc6BBFC+zwR9CKtYGv63Puzsg10L/o12inMY5/2ByzfD6w==";
      };
    };
    "css-select-4.1.3" = {
      name = "css-select";
      packageName = "css-select";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-4.1.3.tgz";
        sha512 = "gT3wBNd9Nj49rAbmtFHj1cljIAOLYSX1nZ8CB7TBO3INYckygm5B7LISU/szY//YmdiSLbJvDLOx9VnMVpMBxA==";
      };
    };
    "css-what-5.0.1" = {
      name = "css-what";
      packageName = "css-what";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-5.0.1.tgz";
        sha512 = "FYDTSHb/7KXsWICVsxdmiExPjCfRC4qRFBdVwv7Ax9hMnvMmEjP9RfxTEZ3qPZGmADDn2vAKSo9UcN1jKVYscg==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "delimit-stream-0.1.0" = {
      name = "delimit-stream";
      packageName = "delimit-stream";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delimit-stream/-/delimit-stream-0.1.0.tgz";
        sha1 = "9b8319477c0e5f8aeb3ce357ae305fc25ea1cd2b";
      };
    };
    "dom-converter-0.2.0" = {
      name = "dom-converter";
      packageName = "dom-converter";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-converter/-/dom-converter-0.2.0.tgz";
        sha512 = "gd3ypIPfOMr9h5jIKq8E3sHOTCjeirnl0WK5ZdS1AW0Odt0b1PaWaHdJ4Qk4klv+YB9aJBS7mESXjFoDQPu6DA==";
      };
    };
    "dom-serializer-1.3.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.3.2.tgz";
        sha512 = "5c54Bk5Dw4qAxNOI1pFEizPSjVsx5+bpJKmL2kPn8JhBUq2q09tTCa3mjijun2NfK78NMouDYNMBkOrPZiS+ig==";
      };
    };
    "domelementtype-2.2.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.2.0.tgz";
        sha512 = "DtBMo82pv1dFtUmHyr48beiuq792Sxohr+8Hm9zoxklYPfa6n0Z3Byjj2IV7bmr2IyqClnqEQhfgHJJ5QF0R5A==";
      };
    };
    "domhandler-4.2.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.2.0.tgz";
        sha512 = "zk7sgt970kzPks2Bf+dwT/PLzghLnsivb9CcxkvR8Mzr66Olr0Ofd8neSbglHJHaHa2MadfoSdNlKYAaafmWfA==";
      };
    };
    "domutils-2.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.7.0.tgz";
        sha512 = "8eaHa17IwJUPAiB+SoTYBo5mCdeMgdcAoXJ59m6DT1vw+5iLS3gNoqYaRowaBKtGVrOF1Jz4yDTgYKLK2kvfJg==";
      };
    };
    "dot-case-3.0.4" = {
      name = "dot-case";
      packageName = "dot-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-case/-/dot-case-3.0.4.tgz";
        sha512 = "Kv5nKlh6yRrdrGvxeJ2e5y2eRUpkUosIW4A2AS38zwSz27zu7ufDwQPi5Jhs3XAlGNetl3bmnGhQsMtkKJnj3w==";
      };
    };
    "electron-to-chromium-1.3.750" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.3.750";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.750.tgz";
        sha512 = "Eqy9eHNepZxJXT+Pc5++zvEi5nQ6AGikwFYDCYwXUFBr+ynJ6pDG7MzZmwGYCIuXShLJM0n4bq+aoKDmvSGJ8A==";
      };
    };
    "emojis-list-3.0.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz";
        sha512 = "/kyM18EfinwXZbno9FyUGeFh87KC8HRQBQGildHZbEuRyWFOmv1U10o9BBp8XVZDVNNuQKyIGIu5ZYAAXJ0V2Q==";
      };
    };
    "enhanced-resolve-5.8.2" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "5.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.8.2.tgz";
        sha512 = "F27oB3WuHDzvR2DOGNTaYy0D5o0cnrv8TeI482VM4kYgQd/FT9lUQwuNsJ0oOHtBUq7eiW5ytqzp7nBFknL+GA==";
      };
    };
    "enquirer-2.3.6" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.3.6.tgz";
        sha512 = "yjNnPr315/FjS4zIsUxYguYUPP2e1NK4d7E7ZOLiyYCcbFBiTMyID+2wvm2w6+pZ/odMA7cRkjhsPbltwBOrLg==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "envinfo-7.8.1" = {
      name = "envinfo";
      packageName = "envinfo";
      version = "7.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/envinfo/-/envinfo-7.8.1.tgz";
        sha512 = "/o+BXHmB7ocbHEAs6F2EnG0ogybVVUdkRunTT2glZU9XAaGmhqskrvKwqXuDfNjEO0LZKWdejEEpnq8aM0tOaw==";
      };
    };
    "es-module-lexer-0.4.1" = {
      name = "es-module-lexer";
      packageName = "es-module-lexer";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-module-lexer/-/es-module-lexer-0.4.1.tgz";
        sha512 = "ooYciCUtfw6/d2w56UVeqHPcoCFAiJdz5XOkYpv/Txl1HMUozpXjz/2RIQgqwKdXNDPSF1W7mJCFse3G+HDyAA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "eslint-scope-5.1.1" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-5.1.1.tgz";
        sha512 = "2NxwbF/hZ0KpepYN0cNbo+FN6XoK7GaHlQhgx/hIZl6Va0bF45RQOOwhLIy8lQDbuCiadSLCBnH2CFYquit5bw==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "estraverse-4.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.3.0.tgz";
        sha512 = "39nnKffWz8xN1BU/2c79n9nB9HDzo0niYUqx6xyqUnyoAnQyyWpOTdZEeiCch8BBu515t4wp9ZmgVfVhn9EBpw==";
      };
    };
    "estraverse-5.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.2.0.tgz";
        sha512 = "BxbNGGNm0RyRYvUdHpIwv9IWzeM9XClbOxwoATuFdOE7ZE6wHL+HQ5T8hoPM+zHvmKzzsEqhgy0GrQ5X13afiQ==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "execa-5.1.1" = {
      name = "execa";
      packageName = "execa";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-5.1.1.tgz";
        sha512 = "8uSpZZocAZRBAPIEINJj3Lo9HyGitllczc27Eh5YYojjMFMn8yHMDMaUHE2Jqfq05D/wucwI4JGURyXt1vchyg==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fastest-levenshtein-1.0.12" = {
      name = "fastest-levenshtein";
      packageName = "fastest-levenshtein";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastest-levenshtein/-/fastest-levenshtein-1.0.12.tgz";
        sha512 = "On2N+BpYJ15xIC974QNVuYGMOlEVt4s0EOI3wwMqOmK1fdDY+FN/zltPV8vosq4ad4c/gJ1KHScUn/6AWIgiow==";
      };
    };
    "find-up-4.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
        sha512 = "PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "glob-to-regexp-0.4.1" = {
      name = "glob-to-regexp";
      packageName = "glob-to-regexp";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-to-regexp/-/glob-to-regexp-0.4.1.tgz";
        sha512 = "lkX1HJXwyMcprw/5YUZc2s7DrpAiHB21/V+E1rHUrVNokkvB6bqMzT0VfV6/86ZNabt1k14YOIaT7nDvOX3Iiw==";
      };
    };
    "graceful-fs-4.2.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.6.tgz";
        sha512 = "nTnJ528pbqxYanhpDYsi4Rd8MAeaBA67+RZ10CM1m3bTAVFEDcd5AuA4a6W5YkGZ1iNXHzZz8T6TBKLeBuNriQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "html-inline-css-webpack-plugin-1.11.0" = {
      name = "html-inline-css-webpack-plugin";
      packageName = "html-inline-css-webpack-plugin";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-inline-css-webpack-plugin/-/html-inline-css-webpack-plugin-1.11.0.tgz";
        sha512 = "VOBX7DOSKTZGwJnToWYhfzq9tt3mbTV0VncCy3APA4ljME20NbkQYiixJMZu782Crpp/kEcml1HbZbYtlXQzgQ==";
      };
    };
    "html-minifier-terser-5.1.1" = {
      name = "html-minifier-terser";
      packageName = "html-minifier-terser";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-minifier-terser/-/html-minifier-terser-5.1.1.tgz";
        sha512 = "ZPr5MNObqnV/T9akshPKbVgyOqLmy+Bxo7juKCfTfnjNniTAMdy4hz21YQqoofMBJD2kdREaqPPdThoR78Tgxg==";
      };
    };
    "html-webpack-plugin-5.3.1" = {
      name = "html-webpack-plugin";
      packageName = "html-webpack-plugin";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-5.3.1.tgz";
        sha512 = "rZsVvPXUYFyME0cuGkyOHfx9hmkFa4pWfxY/mdY38PsBEaVNsRoA+Id+8z6DBDgyv3zaw6XQszdF8HLwfQvcdQ==";
      };
    };
    "htmlparser2-6.1.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-6.1.0.tgz";
        sha512 = "gyyPk6rgonLFEDGoeRgQNaEUvdJ4ktTmmUh/h2t7s+M8oPpIPxgNACWa+6ESR57kXstwqPiCut0V8NRpcwgU7A==";
      };
    };
    "human-signals-2.1.0" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz";
        sha512 = "B4FFZ6q/T2jhhksgkbEW3HBvWIfDW85snkQgawt07S7J5QXTk6BkNV+0yAeZrM5QpMAdYlocGoljn0sJ/WQkFw==";
      };
    };
    "icss-utils-5.1.0" = {
      name = "icss-utils";
      packageName = "icss-utils";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-utils/-/icss-utils-5.1.0.tgz";
        sha512 = "soFhflCVWLfRNOPU3iv5Z9VUdT44xFRbzjLsEzSr5AQmgqPMTHdU3PMT1Cf1ssx8fLNJDA1juftYl+PUcv3MqA==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "import-local-3.0.2" = {
      name = "import-local";
      packageName = "import-local";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-local/-/import-local-3.0.2.tgz";
        sha512 = "vjL3+w0oulAVZ0hBHnxa/Nm5TAurf9YLQJDhqRZyqb+VKGOB6LU8t9H1Nr5CIo16vh9XfJTOoHwU0B71S557gA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inline-chunk-html-plugin-1.1.1" = {
      name = "inline-chunk-html-plugin";
      packageName = "inline-chunk-html-plugin";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-chunk-html-plugin/-/inline-chunk-html-plugin-1.1.1.tgz";
        sha512 = "6W1eGIj8z/Yla6xJx5il6jJfCxMZS3kVkbiLQThbbjdsDLRIWkUVmpnhfW2l6WAwCW+qfy0zoXVGBZM1E5XF3g==";
      };
    };
    "interpret-2.2.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-2.2.0.tgz";
        sha512 = "Ju0Bz/cEia55xDwUWEa8+olFpCiQoypjnQySseKtmjNrnps3P+xfpUmGr90T7yjlVJmOtybRvPXhKMbHr+fWnw==";
      };
    };
    "is-core-module-2.4.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.4.0.tgz";
        sha512 = "6A2fkfq1rfeQZjxrZJGerpLCTHRNEBiSgnu0+obeJpEPZRUooHgsizvzv0ZjJwOz3iWIHdJtVWJ/tmPr3D21/A==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-stream-2.0.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.0.tgz";
        sha512 = "XCoy+WlUr7d1+Z8GgSuXmpuUFC9fOhRXglJMx+dwLKTkL44Cjd4W1Z5P+BQZpr+cR93aGP4S/s7Ftw6Nd/kiEw==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "iso-url-0.4.7" = {
      name = "iso-url";
      packageName = "iso-url";
      version = "0.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/iso-url/-/iso-url-0.4.7.tgz";
        sha512 = "27fFRDnPAMnHGLq36bWTpKET+eiXct3ENlCcdcMdk+mjXrb2kw3mhBUg1B7ewAC0kVzlOPhADzQgz1SE6Tglog==";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "jest-worker-27.0.2" = {
      name = "jest-worker";
      packageName = "jest-worker";
      version = "27.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jest-worker/-/jest-worker-27.0.2.tgz";
        sha512 = "EoBdilOTTyOgmHXtw/cPc+ZrCA0KJMrkXzkrPGNwLmnvvlN1nj7MPrxpT7m+otSv2e1TLaVffzDnE/LB14zJMg==";
      };
    };
    "js-sha256-0.9.0" = {
      name = "js-sha256";
      packageName = "js-sha256";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-sha256/-/js-sha256-0.9.0.tgz";
        sha512 = "sga3MHh9sgQN2+pJ9VYZ+1LPwXOxuBJBA5nrR5/ofPfuiJBE2hnjsaN8se8JznOmGLN2p49Pe5U/ttafcs/apA==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-text-sequence-0.1.1" = {
      name = "json-text-sequence";
      packageName = "json-text-sequence";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-text-sequence/-/json-text-sequence-0.1.1.tgz";
        sha1 = "a72f217dc4afc4629fff5feb304dc1bd51a2f3d2";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "loader-runner-4.2.0" = {
      name = "loader-runner";
      packageName = "loader-runner";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-runner/-/loader-runner-4.2.0.tgz";
        sha512 = "92+huvxMvYlMzMt0iIOukcwYBFpkYJdpl2xsZ7LrlayO7E8SOv+JJUEK17B/dJIHAOLMfh2dZZ/Y18WgmGtYNw==";
      };
    };
    "loader-utils-2.0.0" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-2.0.0.tgz";
        sha512 = "rP4F0h2RaWSvPEkD7BLDFQnvSf+nK+wr3ESUjNTyAGobqrijmW92zc+SO6d4p4B1wh7+B/Jg1mkQe5NYUEHtHQ==";
      };
    };
    "locate-path-5.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
        sha512 = "t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lower-case-2.0.2" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-2.0.2.tgz";
        sha512 = "7fm3l3NAF9WfN6W3JOmf5drwpVqX78JtoGJ3A6W0a6ZnldM41w2fV5D490psKFTpMds8TJse/eHLFFsNHHjHgg==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mime-db-1.48.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.48.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.48.0.tgz";
        sha512 = "FM3QwxV+TnZYQ2aRqhlKBMHxk10lTbMt3bBkMAp54ddrNeVSfcQYOOKuGuy3Ddrm38I04If834fOUSq1yzslJQ==";
      };
    };
    "mime-types-2.1.31" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.31.tgz";
        sha512 = "XGZnNzm3QvgKxa8dpzyhFTHmpP3l5YNusmne07VUOXxou9CqUqYa/HBy124RqtVh/O2pECas/MOcsDgpilPOPg==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "mini-css-extract-plugin-1.6.0" = {
      name = "mini-css-extract-plugin";
      packageName = "mini-css-extract-plugin";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mini-css-extract-plugin/-/mini-css-extract-plugin-1.6.0.tgz";
        sha512 = "nPFKI7NSy6uONUo9yn2hIfb9vyYvkFu95qki0e21DQ9uaqNKDP15DGpK0KnV6wDroWxPHtExrdEwx/yDQ8nVRw==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "nanoid-3.1.23" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.23.tgz";
        sha512 = "FiB0kzdP0FFVGDKlRLEQ1BgDzU87dy5NnzjeW9YZNt+/c3+q82EQDUwniSAUxp/F0gFNI1ZhKU1FqYsMuqZVnw==";
      };
    };
    "neo-async-2.6.2" = {
      name = "neo-async";
      packageName = "neo-async";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.2.tgz";
        sha512 = "Yd3UES5mWCSqR+qNT93S3UoYUkqAZ9lLg8a7g9rimsWmYGK8cVToA4/sF3RrshdyV3sAGMXVUmpMYOw+dLpOuw==";
      };
    };
    "no-case-3.0.4" = {
      name = "no-case";
      packageName = "no-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-3.0.4.tgz";
        sha512 = "fgAN3jGAh+RoxUGZHTSOLJIqUc2wmoBwGR4tbpNAKmmovFoWq0OdRkb0VkldReO2a2iBT/OEulG9XSUc10r3zg==";
      };
    };
    "node-releases-1.1.73" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "1.1.73";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-1.1.73.tgz";
        sha512 = "uW7fodD6pyW2FZNZnp/Z3hvWKeEW1Y8R1+1CnErE8cXFXzl5blBOoVB41CvMer6P6Q0S5FXDwcHgFd1Wj0U9zg==";
      };
    };
    "npm-run-path-4.0.1" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz";
        sha512 = "S48WzZW777zhNIrn7gxOlISNAqi9ZC/uQFnRdbeIHhZhCA6UqpkOT8T1G7BvfdgP4Er8gF4sUbaS0i7QvIfCWw==";
      };
    };
    "nth-check-2.0.0" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-2.0.0.tgz";
        sha512 = "i4sc/Kj8htBrAiH1viZ0TgU8Y5XqCaV/FziYK6TBczxmeKm3AEFWqqF3195yKudrarqy7Zu80Ra5dobFjn9X/Q==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "p-limit-2.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
        sha512 = "//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "p-locate-4.1.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
        sha512 = "R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "pako-2.0.3" = {
      name = "pako";
      packageName = "pako";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-2.0.3.tgz";
        sha512 = "WjR1hOeg+kki3ZIOjaf4b5WVcay1jaliKSYiEaB1XzwhMQZJxRdQRv0V31EKBYlxb4T7SK3hjfc/jxyU64BoSw==";
      };
    };
    "param-case-3.0.4" = {
      name = "param-case";
      packageName = "param-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/param-case/-/param-case-3.0.4.tgz";
        sha512 = "RXlj7zCYokReqWpOPH9oYivUzLYZ5vAPIfEmCTNViosC78F8F0H9y7T7gG2M39ymgutxF5gcFEsyZQSph9Bp3A==";
      };
    };
    "pascal-case-3.1.2" = {
      name = "pascal-case";
      packageName = "pascal-case";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascal-case/-/pascal-case-3.1.2.tgz";
        sha512 = "uWlGT3YSnK9x3BQJaOdcZwrnV6hPpd8jFH1/ucpiLRPh/2zCVJKS19E4GvYHvaCcACn3foXZ0cLB9Wrx1KGe5g==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "pkg-dir-4.2.0" = {
      name = "pkg-dir";
      packageName = "pkg-dir";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkg-dir/-/pkg-dir-4.2.0.tgz";
        sha512 = "HRDzbaKjC+AOWVXxAU/x54COGeIv9eb+6CkDSQoNTt4XyWoIJvuPsXizxu/Fr23EiekbtZwmh1IcIG/l/a10GQ==";
      };
    };
    "postcss-8.3.0" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.3.0.tgz";
        sha512 = "+ogXpdAjWGa+fdYY5BQ96V/6tAo+TdSSIMP5huJBIygdWwKtVoB5JWZ7yUd4xZ8r+8Kvvx4nyg/PQ071H4UtcQ==";
      };
    };
    "postcss-modules-extract-imports-3.0.0" = {
      name = "postcss-modules-extract-imports";
      packageName = "postcss-modules-extract-imports";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-extract-imports/-/postcss-modules-extract-imports-3.0.0.tgz";
        sha512 = "bdHleFnP3kZ4NYDhuGlVK+CMrQ/pqUm8bx/oGL93K6gVwiclvX5x0n76fYMKuIGKzlABOy13zsvqjb0f92TEXw==";
      };
    };
    "postcss-modules-local-by-default-4.0.0" = {
      name = "postcss-modules-local-by-default";
      packageName = "postcss-modules-local-by-default";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-local-by-default/-/postcss-modules-local-by-default-4.0.0.tgz";
        sha512 = "sT7ihtmGSF9yhm6ggikHdV0hlziDTX7oFoXtuVWeDd3hHObNkcHRo9V3yg7vCAY7cONyxJC/XXCmmiHHcvX7bQ==";
      };
    };
    "postcss-modules-scope-3.0.0" = {
      name = "postcss-modules-scope";
      packageName = "postcss-modules-scope";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-scope/-/postcss-modules-scope-3.0.0.tgz";
        sha512 = "hncihwFA2yPath8oZ15PZqvWGkWf+XUfQgUGamS4LqoP1anQLOsOJw0vr7J7IwLpoY9fatA2qiGUGmuZL0Iqlg==";
      };
    };
    "postcss-modules-values-4.0.0" = {
      name = "postcss-modules-values";
      packageName = "postcss-modules-values";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-values/-/postcss-modules-values-4.0.0.tgz";
        sha512 = "RDxHkAiEGI78gS2ofyvCsu7iycRv7oqw5xMWn9iMoR0N/7mf9D50ecQqUo5BZ9Zh2vH4bCUR/ktCqbB9m8vJjQ==";
      };
    };
    "postcss-selector-parser-6.0.6" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.6.tgz";
        sha512 = "9LXrvaaX3+mcv5xkg5kFwqSzSH1JIObIx51PrndZwlmznwXRfxMddDvo9gve3gVR8ZTKgoFDdWkbRFmEhT4PMg==";
      };
    };
    "postcss-value-parser-4.1.0" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-4.1.0.tgz";
        sha512 = "97DXOFbQJhk71ne5/Mt6cOu6yxsSfM0QGQyl0L25Gca4yGWEGJaig7l7gbCX623VqTBNGLRLaVUCnNkcedlRSQ==";
      };
    };
    "pretty-error-2.1.2" = {
      name = "pretty-error";
      packageName = "pretty-error";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-error/-/pretty-error-2.1.2.tgz";
        sha512 = "EY5oDzmsX5wvuynAByrmY0P0hcp+QpnAKbJng2A2MPjVKXCxrDSUkzghVJ4ZGPIv+JC4gX8fPUWscC0RtjsWGw==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "raw-loader-4.0.2" = {
      name = "raw-loader";
      packageName = "raw-loader";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-loader/-/raw-loader-4.0.2.tgz";
        sha512 = "ZnScIV3ag9A4wPX/ZayxL/jZH+euYb6FcUinPcgiQW0+UBtEv0O6Q3lGd3cqJ+GHH+rksEv3Pj99oxJ3u3VIKA==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "rechoir-0.7.0" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.7.0.tgz";
        sha512 = "ADsDEH2bvbjltXEP+hTIAmeFekTFK0V2BTxMkok6qILyAJEXV0AFfoWcAq4yfll5VdIMd/RVXq0lR+wQi5ZU3Q==";
      };
    };
    "relateurl-0.2.7" = {
      name = "relateurl";
      packageName = "relateurl";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/relateurl/-/relateurl-0.2.7.tgz";
        sha1 = "54dbf377e51440aca90a4cd274600d3ff2d888a9";
      };
    };
    "renderkid-2.0.6" = {
      name = "renderkid";
      packageName = "renderkid";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/renderkid/-/renderkid-2.0.6.tgz";
        sha512 = "GIis2GBr/ho0pFNf57D4XM4+PgnQuTii0WCPjEZmZfKivzUfGuRdjN2aQYtYMiNggHmNyBve+thFnNR1iBRcKg==";
      };
    };
    "resolve-1.20.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz";
        sha512 = "wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==";
      };
    };
    "resolve-cwd-3.0.0" = {
      name = "resolve-cwd";
      packageName = "resolve-cwd";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-cwd/-/resolve-cwd-3.0.0.tgz";
        sha512 = "OrZaX2Mb+rJCpH/6CpSqt9xFVpN++x01XnN2ie9g6P5/3xelLAkXWVADpdz1IHD/KFfEXyE6V0U01OQ3UO2rEg==";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "schema-utils-3.0.0" = {
      name = "schema-utils";
      packageName = "schema-utils";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/schema-utils/-/schema-utils-3.0.0.tgz";
        sha512 = "6D82/xSzO094ajanoOSbe4YvXWMfn2A//8Y1+MUqFAJul5Bs+yn36xbK9OtNDcRVSBJ9jjeoXftM6CfztsjOAA==";
      };
    };
    "semver-7.3.5" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz";
        sha512 = "PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==";
      };
    };
    "serialize-javascript-5.0.1" = {
      name = "serialize-javascript";
      packageName = "serialize-javascript";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-javascript/-/serialize-javascript-5.0.1.tgz";
        sha512 = "SaaNal9imEO737H2c05Og0/8LUXG7EnsZyMa8MzkmuHoELfT6txuj0cMqRj6zfPKnmQ1yasR4PCJc8x+M4JSPA==";
      };
    };
    "shallow-clone-3.0.1" = {
      name = "shallow-clone";
      packageName = "shallow-clone";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shallow-clone/-/shallow-clone-3.0.1.tgz";
        sha512 = "/6KqX+GVUdqPuPPd2LxDDxzX6CAbjJehAAOKlNpqqUpAqPM6HeL8f+o3a+JsyGjn2lv0WY8UsTgUJjU9Ok55NA==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "simple-cbor-0.4.1" = {
      name = "simple-cbor";
      packageName = "simple-cbor";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-cbor/-/simple-cbor-0.4.1.tgz";
        sha512 = "rijcxtwx2b4Bje3sqeIqw5EeW7UlOIC4YfOdwqIKacpvRQ/D78bWg/4/0m5e0U91oKvlGh7LlJuZCu07ISCC7w==";
      };
    };
    "source-list-map-2.0.1" = {
      name = "source-list-map";
      packageName = "source-list-map";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-list-map/-/source-list-map-2.0.1.tgz";
        sha512 = "qnQ7gVMxGNxsiL4lEuJwe/To8UnK7fAnmbGEEH8RpLouuKbeEm0lhbQVFIrNSuB+G7tVrAlVsZgETT5nljf+Iw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.3" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.3.tgz";
        sha512 = "CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==";
      };
    };
    "source-map-js-0.6.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-0.6.2.tgz";
        sha512 = "/3GptzWzu0+0MBQFrDKzw/DvvMTUORvgY6k6jd/VS6iCR4RDTKWH6v6WPwQoUO8667uQEf9Oe38DxAYWY5F/Ug==";
      };
    };
    "source-map-support-0.5.19" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.19.tgz";
        sha512 = "Wonm7zOCIJzBGQdB+thsPar0kYuCIzYvxZwlBa87yi/Mdjv7Tip2cyVbLj5o0cFPN4EVkuTwb3GDDyUx2DGnGw==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "strip-final-newline-2.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz";
        sha512 = "BrpvfNAE3dcvq7ll3xVumzjKjZQ5tI1sEUIKr3Uoks0XUl45St3FlatVqef9prk4jRDzhW6WZg+3bk93y6pLjA==";
      };
    };
    "style-loader-2.0.0" = {
      name = "style-loader";
      packageName = "style-loader";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-loader/-/style-loader-2.0.0.tgz";
        sha512 = "Z0gYUJmzZ6ZdRUqpg1r8GsaFKypE+3xAzuFeMuoHgjc9KZv3wMyCRjQIWEbhoFSq7+7yoHXySDJyyWQaPajeiQ==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "tapable-2.2.0" = {
      name = "tapable";
      packageName = "tapable";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-2.2.0.tgz";
        sha512 = "FBk4IesMV1rBxX2tfiK8RAmogtWn53puLOQlvO8XuwlgxcYbP4mVPS9Ph4aeamSyyVjOl24aYWAuc8U5kCVwMw==";
      };
    };
    "terser-4.8.0" = {
      name = "terser";
      packageName = "terser";
      version = "4.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-4.8.0.tgz";
        sha512 = "EAPipTNeWsb/3wLPeup1tVPaXfIaU68xMnVdPafIL1TV05OhASArYyIfFvnvJCNrR2NIOvDVNNTFRa+Re2MWyw==";
      };
    };
    "terser-5.7.0" = {
      name = "terser";
      packageName = "terser";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.7.0.tgz";
        sha512 = "HP5/9hp2UaZt5fYkuhNBR8YyRcT8juw8+uFbAme53iN9hblvKnLUTKkmwJG6ocWpIKf8UK4DoeWG4ty0J6S6/g==";
      };
    };
    "terser-webpack-plugin-5.1.3" = {
      name = "terser-webpack-plugin";
      packageName = "terser-webpack-plugin";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-5.1.3.tgz";
        sha512 = "cxGbMqr6+A2hrIB5ehFIF+F/iST5ZOxvOmy9zih9ySbP1C2oEWQSOUS+2SNBTjzx5xLKO4xnod9eywdfq1Nb9A==";
      };
    };
    "tslib-2.2.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.2.0.tgz";
        sha512 = "gS9GVHRU+RGn5KQM2rllAlR3dU6m7AcpJKdtH8gFvQiC4Otgk98XnmMU+nZenHt/+VhnBPWwgrJsyrdcw6i23w==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utila-0.4.0" = {
      name = "utila";
      packageName = "utila";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utila/-/utila-0.4.0.tgz";
        sha1 = "8a16a05d445657a3aea5eecc5b12a4fa5379772c";
      };
    };
    "v8-compile-cache-2.3.0" = {
      name = "v8-compile-cache";
      packageName = "v8-compile-cache";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache/-/v8-compile-cache-2.3.0.tgz";
        sha512 = "l8lCEmLcLYZh4nbunNZvQCJc5pv7+RCwa8q/LdUx8u7lsWvPDKmpodJAJNwkAhJC//dFY48KuIEmjtd4RViDrA==";
      };
    };
    "watchpack-2.2.0" = {
      name = "watchpack";
      packageName = "watchpack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/watchpack/-/watchpack-2.2.0.tgz";
        sha512 = "up4YAn/XHgZHIxFBVCdlMiWDj6WaLKpwVeGQk2I5thdYxF/KmF0aaz6TfJZ/hfl1h/XlcDr7k1KH7ThDagpFaA==";
      };
    };
    "webpack-5.24.4" = {
      name = "webpack";
      packageName = "webpack";
      version = "5.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack/-/webpack-5.24.4.tgz";
        sha512 = "RXOdxF9hFFFhg47BryCgyFrEyyu7Y/75/uiI2DoUiTMqysK+WczVSTppvkR47oZcmI/DPaXCiCiaXBP8QjkNpA==";
      };
    };
    "webpack-cli-4.5.0" = {
      name = "webpack-cli";
      packageName = "webpack-cli";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-cli/-/webpack-cli-4.5.0.tgz";
        sha512 = "wXg/ef6Ibstl2f50mnkcHblRPN/P9J4Nlod5Hg9HGFgSeF8rsqDGHJeVe4aR26q9l62TUJi6vmvC2Qz96YJw1Q==";
      };
    };
    "webpack-merge-5.7.3" = {
      name = "webpack-merge";
      packageName = "webpack-merge";
      version = "5.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-merge/-/webpack-merge-5.7.3.tgz";
        sha512 = "6/JUQv0ELQ1igjGDzHkXbVDRxkfA57Zw7PfiupdLFJYrgFqY5ZP8xxbpp2lU3EPwYx89ht5Z/aDkD40hFCm5AA==";
      };
    };
    "webpack-sources-1.4.3" = {
      name = "webpack-sources";
      packageName = "webpack-sources";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-sources/-/webpack-sources-1.4.3.tgz";
        sha512 = "lgTS3Xhv1lCOKo7SA5TjKXMjpSM4sBjNV5+q2bqesbSPs5FjGmU6jjtBSkX9b4qW87vDIsCIlUPOEhbZrMdjeQ==";
      };
    };
    "webpack-sources-2.3.0" = {
      name = "webpack-sources";
      packageName = "webpack-sources";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-sources/-/webpack-sources-2.3.0.tgz";
        sha512 = "WyOdtwSvOML1kbgtXbTDnEW0jkJ7hZr/bDByIwszhWd/4XX1A3XMkrbFMsuH4+/MfLlZCUzlAdg4r7jaGKEIgQ==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wildcard-2.0.0" = {
      name = "wildcard";
      packageName = "wildcard";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wildcard/-/wildcard-2.0.0.tgz";
        sha512 = "JcKqAHLPxcdb9KM49dufGXn2x3ssnfjbcaQdLlfZsL9rH9wgDQjUtDxbo8NE0F6SFvydeu1VhZe7hZuHsB2/pw==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
    "zbar.wasm-2.0.3" = {
      name = "zbar.wasm";
      packageName = "zbar.wasm";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/zbar.wasm/-/zbar.wasm-2.0.3.tgz";
        sha512 = "kpdc9S4rSO9fxtuShJQMNFYDcT+sA399oXBoWfPtUvfl1ytxrVs/2aklfrBsxmFPcvrFejLb3ZlwrubTNb17xg==";
      };
    };
  };
  args = {
    name = "ic-qr-scanner";
    packageName = "ic-qr-scanner";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      (sources."@dfinity/agent-0.9.0" // {
        dependencies = [
          (sources."borc-2.1.2" // {
            dependencies = [
              sources."buffer-5.7.1"
            ];
          })
          sources."iso-url-0.4.7"
          sources."json-text-sequence-0.1.1"
        ];
      })
      sources."@dfinity/candid-0.9.0"
      sources."@dfinity/principal-0.9.0"
      sources."@discoveryjs/json-ext-0.5.3"
      sources."@types/eslint-7.2.13"
      sources."@types/eslint-scope-3.7.0"
      sources."@types/estree-0.0.46"
      sources."@types/html-minifier-terser-5.1.1"
      sources."@types/json-schema-7.0.7"
      sources."@types/node-15.12.2"
      sources."@webassemblyjs/ast-1.11.0"
      sources."@webassemblyjs/floating-point-hex-parser-1.11.0"
      sources."@webassemblyjs/helper-api-error-1.11.0"
      sources."@webassemblyjs/helper-buffer-1.11.0"
      sources."@webassemblyjs/helper-numbers-1.11.0"
      sources."@webassemblyjs/helper-wasm-bytecode-1.11.0"
      sources."@webassemblyjs/helper-wasm-section-1.11.0"
      sources."@webassemblyjs/ieee754-1.11.0"
      sources."@webassemblyjs/leb128-1.11.0"
      sources."@webassemblyjs/utf8-1.11.0"
      sources."@webassemblyjs/wasm-edit-1.11.0"
      sources."@webassemblyjs/wasm-gen-1.11.0"
      sources."@webassemblyjs/wasm-opt-1.11.0"
      sources."@webassemblyjs/wasm-parser-1.11.0"
      sources."@webassemblyjs/wast-printer-1.11.0"
      sources."@webpack-cli/configtest-1.0.3"
      sources."@webpack-cli/info-1.2.4"
      sources."@webpack-cli/serve-1.4.0"
      sources."@xtuc/ieee754-1.2.0"
      sources."@xtuc/long-4.2.2"
      sources."acorn-8.3.0"
      sources."ajv-6.12.6"
      sources."ajv-keywords-3.5.2"
      sources."ansi-colors-4.1.1"
      sources."ansi-regex-5.0.0"
      sources."base64-arraybuffer-0.2.0"
      sources."base64-js-1.5.1"
      sources."big.js-5.2.2"
      (sources."bigint-json-native-0.4.2" // {
        dependencies = [
          sources."bignumber.js-7.2.1"
        ];
      })
      sources."bignumber.js-9.0.1"
      sources."boolbase-1.0.0"
      sources."browserslist-4.16.6"
      sources."buffer-6.0.3"
      sources."buffer-from-1.1.1"
      sources."buffer-pipe-0.0.4"
      sources."camel-case-4.1.2"
      sources."caniuse-lite-1.0.30001236"
      sources."chrome-trace-event-1.0.3"
      sources."clean-css-4.2.3"
      sources."clone-deep-4.0.1"
      sources."colorette-1.2.2"
      sources."commander-2.20.3"
      sources."cross-spawn-7.0.3"
      sources."css-loader-5.2.6"
      sources."css-select-4.1.3"
      sources."css-what-5.0.1"
      sources."cssesc-3.0.0"
      sources."delimit-stream-0.1.0"
      sources."dom-converter-0.2.0"
      sources."dom-serializer-1.3.2"
      sources."domelementtype-2.2.0"
      sources."domhandler-4.2.0"
      sources."domutils-2.7.0"
      sources."dot-case-3.0.4"
      sources."electron-to-chromium-1.3.750"
      sources."emojis-list-3.0.0"
      sources."enhanced-resolve-5.8.2"
      sources."enquirer-2.3.6"
      sources."entities-2.2.0"
      sources."envinfo-7.8.1"
      sources."es-module-lexer-0.4.1"
      sources."escalade-3.1.1"
      sources."eslint-scope-5.1.1"
      (sources."esrecurse-4.3.0" // {
        dependencies = [
          sources."estraverse-5.2.0"
        ];
      })
      sources."estraverse-4.3.0"
      sources."events-3.3.0"
      sources."execa-5.1.1"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fastest-levenshtein-1.0.12"
      sources."find-up-4.1.0"
      sources."function-bind-1.1.1"
      sources."get-stream-6.0.1"
      sources."glob-to-regexp-0.4.1"
      sources."graceful-fs-4.2.6"
      sources."has-1.0.3"
      sources."has-flag-4.0.0"
      sources."he-1.2.0"
      sources."html-inline-css-webpack-plugin-1.11.0"
      (sources."html-minifier-terser-5.1.1" // {
        dependencies = [
          sources."commander-4.1.1"
          (sources."terser-4.8.0" // {
            dependencies = [
              sources."commander-2.20.3"
            ];
          })
        ];
      })
      sources."html-webpack-plugin-5.3.1"
      sources."htmlparser2-6.1.0"
      sources."human-signals-2.1.0"
      sources."icss-utils-5.1.0"
      sources."ieee754-1.2.1"
      sources."import-local-3.0.2"
      sources."inherits-2.0.4"
      sources."inline-chunk-html-plugin-1.1.1"
      sources."interpret-2.2.0"
      sources."is-core-module-2.4.0"
      sources."is-plain-object-2.0.4"
      sources."is-stream-2.0.0"
      sources."isexe-2.0.0"
      sources."isobject-3.0.1"
      sources."jest-worker-27.0.2"
      sources."js-sha256-0.9.0"
      sources."json-parse-better-errors-1.0.2"
      sources."json-schema-traverse-0.4.1"
      sources."json5-2.2.0"
      sources."kind-of-6.0.3"
      sources."loader-runner-4.2.0"
      sources."loader-utils-2.0.0"
      sources."locate-path-5.0.0"
      sources."lodash-4.17.21"
      sources."lower-case-2.0.2"
      sources."lru-cache-6.0.0"
      sources."merge-stream-2.0.0"
      sources."mime-db-1.48.0"
      sources."mime-types-2.1.31"
      sources."mimic-fn-2.1.0"
      (sources."mini-css-extract-plugin-1.6.0" // {
        dependencies = [
          sources."webpack-sources-1.4.3"
        ];
      })
      sources."minimist-1.2.5"
      sources."nanoid-3.1.23"
      sources."neo-async-2.6.2"
      sources."no-case-3.0.4"
      sources."node-releases-1.1.73"
      sources."npm-run-path-4.0.1"
      sources."nth-check-2.0.0"
      sources."onetime-5.1.2"
      sources."p-limit-3.1.0"
      (sources."p-locate-4.1.0" // {
        dependencies = [
          sources."p-limit-2.3.0"
        ];
      })
      sources."p-try-2.2.0"
      sources."pako-2.0.3"
      sources."param-case-3.0.4"
      sources."pascal-case-3.1.2"
      sources."path-exists-4.0.0"
      sources."path-key-3.1.1"
      sources."path-parse-1.0.7"
      sources."pkg-dir-4.2.0"
      sources."postcss-8.3.0"
      sources."postcss-modules-extract-imports-3.0.0"
      sources."postcss-modules-local-by-default-4.0.0"
      sources."postcss-modules-scope-3.0.0"
      sources."postcss-modules-values-4.0.0"
      sources."postcss-selector-parser-6.0.6"
      sources."postcss-value-parser-4.1.0"
      sources."pretty-error-2.1.2"
      sources."punycode-2.1.1"
      sources."randombytes-2.1.0"
      sources."raw-loader-4.0.2"
      sources."readable-stream-3.6.0"
      sources."rechoir-0.7.0"
      sources."relateurl-0.2.7"
      sources."renderkid-2.0.6"
      sources."resolve-1.20.0"
      sources."resolve-cwd-3.0.0"
      sources."resolve-from-5.0.0"
      sources."safe-buffer-5.2.1"
      sources."schema-utils-3.0.0"
      sources."semver-7.3.5"
      sources."serialize-javascript-5.0.1"
      sources."shallow-clone-3.0.1"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-3.0.3"
      sources."simple-cbor-0.4.1"
      sources."source-list-map-2.0.1"
      sources."source-map-0.6.1"
      sources."source-map-js-0.6.2"
      sources."source-map-support-0.5.19"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.0"
      sources."strip-final-newline-2.0.0"
      sources."style-loader-2.0.0"
      sources."supports-color-8.1.1"
      sources."tapable-2.2.0"
      (sources."terser-5.7.0" // {
        dependencies = [
          sources."source-map-0.7.3"
        ];
      })
      sources."terser-webpack-plugin-5.1.3"
      sources."tslib-2.2.0"
      sources."uri-js-4.4.1"
      sources."util-deprecate-1.0.2"
      sources."utila-0.4.0"
      sources."v8-compile-cache-2.3.0"
      sources."watchpack-2.2.0"
      sources."webpack-5.24.4"
      (sources."webpack-cli-4.5.0" // {
        dependencies = [
          sources."commander-7.2.0"
        ];
      })
      sources."webpack-merge-5.7.3"
      sources."webpack-sources-2.3.0"
      sources."which-2.0.2"
      sources."wildcard-2.0.0"
      sources."yallist-4.0.0"
      sources."yocto-queue-0.1.0"
      sources."zbar.wasm-2.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "IC Transaction Scanner";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
